include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: docker:20.10.6

services:
  - docker:dind

before_script:
  - apk add --no-cache py3-pip
  - pip install --no-cache-dir docker-compose
  - pip install docker-compose

compose services:
  script:
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true
