image: docker:20.10.6

services:
  - docker:dind

stages:
  - docker

before_script:
  - apk update

cache:
  paths:
    - ~/.cache

build containers:
  stage: docker
  before_script:
    - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make rust cargo
    - pip install docker-compose
  script:
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true
