include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

image: docker/compose:latest

services:
  - docker:dind

stages:
  - test
  - build

before_script:
  - apk update

cache:
  paths:
    - ~/.cache

smoke test docker containers:
  stage: test
  script:
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true
